WITH MAR_MAY_CONN AS (
SELECT DISTINCT HP.DIVISION, HP.REGION, HP.DMA, HP.CITY, AAV.MONTH_END_DT
					,  AAV.TENURE_DESC, AAV.HSI_TIER, AAV.ACCOUNT_NUMBER
                /*
                , CASE WHEN HP.ETHNIC_ROLL_UP = 'HISP' THEN 'HISP'
                WHEN HP.ETHNIC_ROLL_UP = 'AFAM' THEN 'AF_AM'
                WHEN HP.ETHNIC_ROLL_UP IN ('PCAS','MEST','SOAS') THEN 'ASIA_ME'
               ELSE 'OTHER_HP' END AS ETHNICITY
                , CASE WHEN HP.demo_INCOME_CODE IN ('<15K','15-25K','25-35K','35-50K') THEN 'INC_CONST'
                WHEN HP.demo_INCOME_CODE IN ('50-75K','75-100K','100-125K')  THEN 'DISP_INC'
                WHEN HP.demo_INCOME_CODE IN ('125-150K','150-175K','175-200K') THEN 'INC_HI'
                WHEN HP.demo_INCOME_CODE IN ('200-250K','250K+')  THEN 'INC_LUX'
                ELSE 'UNK' END AS INCOME
                */
                , HP.DWELL_TYPE_GROUP AS DWELL
                
              
                --, COUNT(DISTINCT AAV.ACCOUNT_NUMBER) AS CONNECTS
                
                FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY AS AAV 
LEFT JOIN ndw_rosetta_views.rosetta_homes_passed_current AS HP
ON HP.LOCATION_ID = AAV.LOCATION_ID
WHERE MONTH(aav.MONTH_END_DT) BETWEEN 2 AND 5 AND YEAR(aav.month_end_dt) > 2019
                AND ORDER_STATUS = 'COMPLETED'
                AND ACTIVITYDETAIL LIKE 'NEW CONNECT'
				--AND FINAL_DISCONNECT_TYPE LIKE 'VOLUNTARY'
				AND INTERNET_ESSENTIALS_IND = 1
                AND HSI_TIER = 'INTERNET ESSENTIALS'
                AND CUSTOMER_TYPE = 'RESIDENTIAL'
				AND DWELL_TYPE_GROUP_BILLER IN ('MDU','SFU')
                AND DIVISION_NAME LIKE '%central%'
                --GROUP BY 1,2,3,4,5,6,7,8,9--,10
				--SAMPLE 500;
				)
				
, DISCO_20 AS (	
				SELECT DISTINCT HP.DIVISION, HP.REGION, HP.DMA, HP.CITY, AAV.MONTH_END_DT
					,  AAV.TENURE_DESC, AAV.HSI_TIER, AAV.ACCOUNT_NUMBER
                , aav.CUSTOMER_ACCOUNT_ID
                , CASE WHEN HP.ETHNIC_ROLL_UP = 'HISP' THEN 'HISP'
                WHEN HP.ETHNIC_ROLL_UP = 'AFAM' THEN 'AF_AM'
                WHEN HP.ETHNIC_ROLL_UP IN ('PCAS','MEST','SOAS') THEN 'ASIA_ME'
               ELSE 'OTHER_HP' END AS ETHNICITY
                , CASE WHEN HP.demo_INCOME_CODE IN ('<15K','15-25K','25-35K','35-50K') THEN 'INC_CONST'
                WHEN HP.demo_INCOME_CODE IN ('50-75K','75-100K','100-125K')  THEN 'DISP_INC'
                WHEN HP.demo_INCOME_CODE IN ('125-150K','150-175K','175-200K') THEN 'INC_HI'
                WHEN HP.demo_INCOME_CODE IN ('200-250K','250K+')  THEN 'INC_LUX'
                ELSE 'UNK' END AS INCOME
                
                , HP.DWELL_TYPE_GROUP AS DWELL
                
              
                --, COUNT(DISTINCT AAV.ACCOUNT_NUMBER) AS DISCONNECTS
                
                FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY AS AAV 
							
LEFT JOIN ndw_rosetta_views.rosetta_homes_passed_current AS HP
ON HP.LOCATION_ID = AAV.LOCATION_ID
WHERE YEAR(aav.month_end_dt) > 2019
                AND ORDER_STATUS = 'COMPLETED'
                --AND ACTIVITYDETAIL LIKE 'FULL DISCONNECT'
				AND FINAL_DISCONNECT_TYPE LIKE 'VOLUNTARY'
				AND INTERNET_ESSENTIALS_IND = -1
                AND HSI_TIER = 'INTERNET ESSENTIALS'
				AND DWELL_TYPE_GROUP_BILLER IN ('MDU','SFU')
                AND CUSTOMER_TYPE = 'RESIDENTIAL'
                AND DIVISION_NAME LIKE '%central%'
                --GROUP BY 1,2,3,4,5,6,7,8,9,10,11
				--SAMPLE 500;
				)
				
				
				,PROD AS (
SELECT AP.CUSTOMER_ACCOUNT_ID, PH.PRODUCT_NAME, PH.PRODUCT_TIER_CD, PH.PROD_CATEGORY_CD, PH.LOB
, AP.ACCOUNT_PRODUCT_EFF_DT, AP.ACCOUNT_PRODUCT_END_DT
, CASE WHEN ( (AP.ACCOUNT_PRODUCT_END_DT - AP.ACCOUNT_PRODUCT_EFF_DT) BETWEEN 1 AND 60 AND MONTH(AP.ACCOUNT_PRODUCT_EFF_DT) > 2 ) THEN 1 ELSE 0 END AS CRISIS
FROM NDW_BASE_VIEWS.ACCOUNT_PRODUCT AS AP
JOIN NDW_BASE_VIEWS.PRODUCT_HIERARCHY_V AS PH 
ON AP.PRODUCT_ID = PH.PRODUCT_ID 
WHERE PH.PRODUCT_NAME = 'INTERNET ESSENTIALS'
AND  YEAR(AP.ACCOUNT_PRODUCT_END_DT) > 2019 
AND COURTESY_IND = 'N'
--SAMPLE 500;
)
				
				SEL D.DIVISION, D.REGION, D.DMA, D.CITY, D.MONTH_END_DT AS MONTH_DISCO, C.MONTH_END_DT AS MONTH_CONN
					,  D.TENURE_DESC, D.HSI_TIER
					, D.ETHNICITY, D.INCOME
					, COUNT(DISTINCT D.ACCOUNT_NUMBER) AS DISCONNECTS
					, SUM(PROD.CRISIS) AS CRISIS
					, COUNT(DISTINCT C.ACCOUNT_NUMBER) AS CONNECTS
					FROM MAR_MAY_CONN AS C
					LEFT JOIN DISCO_20 AS D
					ON (D.ACCOUNT_NUMBER = C.ACCOUNT_NUMBER)
					LEFT JOIN PROD
					ON (D.CUSTOMER_ACCOUNT_ID = PROD.CUSTOMER_ACCOUNT_ID)
					WHERE  (D.MONTH_END_DT > C.MONTH_END_DT)
					GROUP BY 1,2,3,4,5,6,7,8,9,10
					--SAMPLE 500;