


WITH PROD AS (
SELECT AP.CUSTOMER_ACCOUNT_ID, PH.PRODUCT_NAME, PH.PRODUCT_TIER_CD, PH.PROD_CATEGORY_CD, PH.LOB
, AP.ACCOUNT_PRODUCT_EFF_DT, AP.ACCOUNT_PRODUCT_END_DT
, CASE WHEN ( (AP.ACCOUNT_PRODUCT_END_DT - AP.ACCOUNT_PRODUCT_EFF_DT) BETWEEN 1 AND 60 AND MONTH(AP.ACCOUNT_PRODUCT_EFF_DT) > 2 ) THEN 1 ELSE 0 END AS CRISIS
FROM NDW_BASE_VIEWS.ACCOUNT_PRODUCT AS AP
JOIN NDW_BASE_VIEWS.PRODUCT_HIERARCHY_V AS PH 
ON AP.PRODUCT_ID = PH.PRODUCT_ID 
WHERE PH.PRODUCT_NAME = 'INTERNET ESSENTIALS'
AND  YEAR(AP.ACCOUNT_PRODUCT_END_DT) > 2019 
AND COURTESY_IND = 'N'
--SAMPLE 500;
)

, ACTIVITY AS (
SELECT AV.EFFECTIVE_DATE, AV.MONTH_END_DT, AV.CUSTOMER_ACCOUNT_ID, AV.ZIP
, HP.CITY, HP.STATE, HP.DMA, HP.DWELL_TYPE_GROUP AS DWELL, HP.DIVISION, HP.REGION
, CASE WHEN HP.demo_INCOME_CODE IN ('<15K','15-25K','25-35K','35-50K') THEN 'INC_CONST'	
                WHEN HP.demo_INCOME_CODE IN ('50-75K','75-100K','100-125K')  THEN 'DISP_INC'	
                WHEN HP.demo_INCOME_CODE IN ('125-150K','150-175K','175-200K') THEN 'INC_HI'	
                WHEN HP.demo_INCOME_CODE IN ('200-250K','250K+')  THEN 'INC_LUX'	
                ELSE 'UNK' END AS INCOME	
FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY AS AV
LEFT JOIN ndw_rosetta_views.rosetta_homes_passed_current AS HP	
ON HP.LOCATION_ID = AV.LOCATION_ID	
WHERE YEAR(AV.MONTH_END_DT) > 2019	
                AND ORDER_STATUS = 'COMPLETED'	
				AND AV.FINAL_DISCONNECT_TYPE LIKE 'VOLUNTARY'
                AND ACTIVITYDETAIL LIKE 'FULL DISCONNECT'	
                AND HSI_TIER = 'INTERNET ESSENTIALS'	
                AND CUSTOMER_TYPE = 'RESIDENTIAL'	
                AND DIVISION_NAME LIKE '%central%'	
				--SAMPLE 500;
)

SEL DISTINCT ACTIVITY.DIVISION, ACTIVITY.REGION, ACTIVITY.CITY, ACTIVITY.MONTH_END_DT, ACTIVITY.ZIP
, ACTIVITY.DWELL, ACTIVITY.INCOME
, PROD.PRODUCT_NAME
, COUNT(DISTINCT PROD.CUSTOMER_ACCOUNT_ID) AS DISCO
, SUM(PROD.CRISIS) AS CRISIS
FROM ACTIVITY
LEFT JOIN PROD
ON PROD.CUSTOMER_ACCOUNT_ID = ACTIVITY.CUSTOMER_ACCOUNT_ID
GROUP BY ACTIVITY.DIVISION, ACTIVITY.REGION, ACTIVITY.CITY, ACTIVITY.MONTH_END_DT
, ACTIVITY.DWELL, ACTIVITY.INCOME
, PROD.PRODUCT_NAME, ACTIVITY.ZIP
;
--SAMPLE 1000;

