	SEL DISTINCT A.DIVISION, A.REGION, A.DMA, A.CITY, A.MONTH_END_DT,
				A.VISIT1 
				, COUNT(DISTINCT A.ACCOUNT_NUMBER) AS DISCOS
				FROM
				(
				SELECT HP.DIVISION, HP.REGION, HP.DMA, HP.CITY, AV.MONTH_END_DT, AV.ACCOUNT_NUMBER
				,SUM (CASE WHEN HP.MONTH_END_DT IN (ADD_MONTHS (AV.MONTH_END_DT, -1),ADD_MONTHS (AV.MONTH_END_DT, -2),ADD_MONTHS (AV.MONTH_END_DT, -3)) THEN HP.TRUCKROLL_TC_CNT ELSE 0 END )AS VISIT1
				--,CASE WHEN HP.MONTH_END_DT = ADD_MONTHS (AV.MONTH_END_DT, -2) THEN HP.TRUCKROLL_TC_CNT ELSE 0 END AS VISIT2
				--, CASE WHEN HP.MONTH_END_DT = ADD_MONTHS (AV.MONTH_END_DT, -3) THEN HP.TRUCKROLL_TC_CNT ELSE 0 END AS VISIT3
				FROM EBI_NSD_VIEWS.NSD_MASTER_DAILY_ACTIVITY AS AV 
LEFT JOIN (
SELECT DIVISION, REGION, DMA, CITY, MONTH_END_DT, ACCOUNT_NUMBER
, CASE WHEN TRUCKROLL_TC_CNT IS NOT NULL THEN TRUCKROLL_TC_CNT ELSE 0 END AS TRUCKROLL_TC_CNT
FROM NDW_ROSETTA_VIEWS.ROSETTA_2020 
WHERE customer_type = 'RESIDENTIAL'
				AND division = 'CENTRAL DIVISION'
)AS HP
ON HP.ACCOUNT_NUMBER = AV.ACCOUNT_NUMBER --AND  HP.MONTH_END_DT = ADD_MONTHS (AV.MONTH_END_DT, -1)
WHERE YEAR(AV.MONTH_END_DT) > 2019	
                AND ORDER_STATUS = 'COMPLETED'
                --AND ACTIVITYDETAIL LIKE 'FULL DISCONNECT'
				AND FINAL_DISCONNECT_TYPE LIKE 'VOLUNTARY'
				--AND INTERNET_ESSENTIALS_IND = -1
				
                AND HSI_TIER <> 'INTERNET ESSENTIALS'
                AND AV.CUSTOMER_TYPE = 'RESIDENTIAL'
				
                AND DIVISION_NAME LIKE '%central%'
                GROUP BY HP.DIVISION, HP.REGION, HP.DMA, HP.CITY, AV.MONTH_END_DT, AV.ACCOUNT_NUMBER, HP.MONTH_END_DT
				) AS A
				WHERE A.DMA IS NOT NULL
				GROUP BY 1,2,3,4,5,6